[package]
name = "slack-mr-reminder"
version = "0.1.0"
authors = ["Mikhail Sakhnov <sahnov.m@gmail.com>"]
edition = "2018"

[dependencies]
restson = "^0.5"
serde = "^1.0"
serde_derive = "^1.0"
clap = "2.32"